name: Try GitHub Action

on: [push]

jobs:
  try-github-action-jira-integration:
    name: Try GitHub Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: john-d-pelingo/jira-link-issue-action@v1
        with:
          atlassian-domain: 'https://rashmingowda95.atlassian.net/'
          GITHUB_TOKEN: ${{github.token}}
          board-name: 'LJGI board'
