on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
         fetch-depth: 0
        
      - name: changelog   
        uses: rashmigowda95/changelog-generator-action@master
        with:
          REPO_NAME: ${{ github.repository }}
          ACCESS_TOKEN: ${{secrets.SNAPSERV_BOT_TOKEN}}
          PATH: '/CHANGELOG.md'
          COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
