on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: changelog   
        uses: srepollock/changelog-generator-action@master
        with:
          REPO_NAME: $ {{ github.repository }}
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PATH: '/CHANGELOG.md'
          COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
