on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - name: Generate changelog
        uses: fabernovel/github-changelog-generator-action@v1.0.0-alpha02
        with:
          options: --token ${{ secrets.GITHUB_TOKEN }}
      - name: Printing changelog
        run: |
         cat CHANGELOG.md 
        
      - name: update chnage
        run: |
          git add CHANGELOG.md
          git commit -m " change log file"
          git push
