on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - name: update the chnagelog
        uses: BobAnkh/auto-generate-changelog@v1.2.3
        with:
          ACCESS_TOKEN: ${{github.token}}
          TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
        
