on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - name: Release new versions using AutoTagBot
        uses: snapserv/action-autotagbot@master
        with:
          api_token: '${{ secrets.SNAPSERV_BOT_TOKEN }}'
          source_file: 'package.json'
          version_pattern: '"version"\s*:\s*"(?<version>[0-9.]+)"'
          tag_format: 'v{version}'    
      - name: update the chnagelog
        uses: rashmigowda95/auto-generate-changelog@master
        with:
          ACCESS_TOKEN: ${{github.token}}
          TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
        
