on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
         fetch-depth: 0
         
      - name: Release new versions using AutoTagBot
        uses: snapserv/action-autotagbot@master
        with:
          api_token: '${{ secrets.SNAPSERV_BOT_TOKEN }}'
          source_file: 'package.json'
          version_pattern: '"version"\s*:\s*"(?<version>[0-9.]+)"'
          tag_format: 'v{version}' 
      - name: update the chnagelog
        uses: BobAnkh/auto-generate-changelog@v1.2.3
        with:
          REPO_NAME: '<YourUserName>/<YourRepoName>'
          ACCESS_TOKEN: ${{github.token}}
          PATH: 'CHANGELOG.md'
          COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
          TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
          
      - name: Jira-integration
        uses: john-d-pelingo/jira-link-issue-action@v1.1.2
        with:
          atlassian-domain: 'https://rashmingowda95.atlassian.net/'
          GITHUB_TOKEN: ${{github.token}}
          board-name: 'LJGI board'   
