name: AutoTagBot

on:
  push:
    branches:
      - master
    paths:
      - package.json

jobs:
  auto-tag-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Release new versions using AutoTagBot
        uses: snapserv/action-autotagbot@master
        with:
          api_token: '${{ secrets.SNAPSERV_BOT_TOKEN }}'
          source_file: 'package.json'
          version_pattern: '"version"\s*:\s*"(?<version>[0-9.]+)"'
          tag_format: 'v{version}'
      - name: Generate changelog
        uses: fabernovel/github-changelog-generator-action@v1.0.0-alpha02
        with:
      # You can pass any parameters from https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples#additional-options
          options: --token ${{ secrets.SNAPSERV_BOT_TOKEN }}
